Refactor Debian packaging usins debhelper.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,24 +1,80 @@
 #!/bin/sh
-
-if [ "$1" = "configure" ];then
-	mkdir -m 0750 -p /var/{log,run}/sftp-cloudfs
-	chown daemon: /var/{log,run}/sftp-cloudfs
-fi
-
-# Automatically added by dh_pysupport
-if which update-python-modules >/dev/null 2>&1; then
-	update-python-modules -a
-fi
-# End automatically added section
+# postinst script for sftpcloudfs
+#
+# see: dh_installdeb(1)
 
 set -e
-# Automatically added by dh_installinit
-if [ -x "/etc/init.d/python-sftp-cloudfs" ]; then
-	update-rc.d python-sftp-cloudfs defaults >/dev/null
-	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-		invoke-rc.d python-sftp-cloudfs start || exit $?
-	else
-		/etc/init.d/python-sftp-cloudfs start || exit $?
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+	if ! getent group sftpcloudfs > /dev/null 2>&1
+	then
+		addgroup --system sftpcloudfs >/dev/null
 	fi
-fi
-# End automatically added section
+	if ! getent passwd sftpcloudfs > /dev/null 2>&1
+	then
+	        adduser --system --home /var/log/sftpcloudfs --ingroup sftpcloudfs --no-create-home --shell /bin/false sftpcloudfs > /dev/null 2>&1
+	fi
+
+	# RAS key file directory
+	mkdir -m 0700 -p /etc/sftpcloudfs
+	chown -R sftpcloudfs:sftpcloudfs /etc/sftpcloudfs
+
+	# log directory
+	mkdir -m 0700 -p /var/log/sftpcloudfs
+	touch /var/log/sftpcloudfs/sftpcloudfs.log
+	chmod 0640 /var/log/sftpcloudfs/sftpcloudfs.log
+	chown -R sftpcloudfs:sftpcloudfs /var/log/sftpcloudfs
+
+	# pid file directory
+	mkdir -m 0700 -p /var/run/sftpcloudfs
+	chown -R sftpcloudfs:sftpcloudfs /var/run/sftpcloudfs
+
+	if which update-python-modules >/dev/null 2>&1; then
+        	update-python-modules --post-install
+	fi
+
+	if [ -x "/etc/init.d/sftpcloudfs" ]; then
+        	update-rc.d sftpcloudfs defaults >/dev/null
+        #	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+        #        	invoke-rc.d sftpcloudfs start || exit $?
+        #	else
+        #        	/etc/init.d/sftpcloudfs start || exit $?
+        #	fi
+	fi
+
+	echo "*******************************************"
+	echo "Your UID is:"
+	id -u sftpcloudfs
+	echo "Your GID is:"
+	id -g sftpcloudfs
+	echo "Update your configuration file accordingly."
+	echo "*******************************************"
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
